
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[371] =
    {   0,
        0,    0,    0,    0,   98,   97,    4,    5,    5,   21,
       97,   95,   40,    7,   97,   31,   49,   54,   42,   16,
       37,   17,   52,   62,   62,   15,   51,   33,   19,   24,
       47,   32,   50,   45,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       30,   11,   48,   61,    3,    3,    3,    5,   22,    0,
        0,   94,    0,   95,   41,    8,    9,    0,    0,    0,
        0,   55,   44,   43,   39,   38,   10,    0,   23,    1,
       96,   53,   23,   62,    0,    0,   23,    0,   62,    0,
        0,    0,    0,   62,    0,   18,   35,   34,   20,   25,

       26,   46,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   80,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   13,   12,    3,
        2,   94,    0,    0,    0,   94,    0,    0,   14,   14,
        0,    0,    0,    0,    6,   23,   23,    0,    0,   96,
       96,   96,   23,   23,    0,   62,   62,   62,    0,    0,
       62,    0,   23,    0,   62,   62,   62,    0,   62,   62,
        0,   62,   36,   27,   28,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   81,

       95,   77,   95,   75,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   60,   59,   95,   95,
       95,    0,    0,    0,    0,    0,    0,    0,    0,   23,
       23,    0,    0,   23,   62,   62,   62,    0,   23,   23,
        0,    0,    0,   62,   62,   62,    0,    0,   62,   62,
        0,   62,   62,    0,    0,    0,   62,   62,    0,   62,
        0,   29,   95,   95,   95,   77,   95,   95,   95,   95,
       86,   95,   95,   95,   95,   95,   95,   95,   74,   95,
       95,   95,   95,   95,   95,   95,   95,   66,   95,   92,
       58,   95,   95,    0,    0,    0,   23,    0,   23,    0,

        0,    0,    0,   23,    0,    0,   95,   95,   90,   89,
       88,   95,   95,   95,   84,   82,   95,   95,   95,   95,
       95,   95,   95,   95,   68,   95,   65,   57,   56,    0,
       23,   23,    0,   93,   95,   95,   95,   95,   95,   78,
       95,   95,   95,   71,   70,   69,   95,   64,   63,   91,
       95,   85,   83,   95,   95,   73,   72,   95,   87,   95,
       95,   95,   95,   76,   95,   79,   95,   95,   67,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        1,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,    9,    1,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   25,   25,   25,   25,   26,   26,   27,   28,   29,
       30,   31,   32,    1,   33,   34,   33,   35,   36,   37,
       10,   10,   10,   10,   10,   38,   10,   10,   10,   39,
       10,   10,   10,   10,   10,   10,   10,   40,   10,   10,
       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   10,   55,   56,   57,   58,
       59,   60,   10,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        1,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    5,    5,    5,    5,    5,    6,    7,    3,
        1,    8,    1,    1,    9,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    7,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[385] =
    {   0,
        0,    0,   68,   69,  861,  959,  959,  959,  856,  829,
       74,    0,  828,   69,   87,  959,  959,  827,   65,  959,
       67,   81,   92,  130,  178,  829,  959,   80,  819,   81,
      959,  959,  959,  817,  784,   56,   72,  783,   63,   81,
       63,  782,   38,   82,  790,   70,   86,   98,  785,  783,
      959,  111,  959,  959,  959,  831,  812,  959,  959,  182,
      228,  823,  289,    0,  959,  959,  959,  817,  815,  814,
      234,  959,  959,  959,  959,  959,  959,  806,  330,  959,
       90,  959,  360,  226,  138,  136,  959,  243,  959,  792,
      251,  149,  791,  256,  261,  959,  780,  959,  959,  959,

      143,  959,  746,  748,  750,  735,  734,  750,  737,  723,
      716,  717,  714,  720,  717,  714,  711,    0,  711,  704,
      702,  685,  693,  685,  690,  688,  670,  672,  684,  652,
      652,  135,  126,  647,  652,  651,  654,  959,  959,  959,
      959,  959,  202,  315,  330,  385,  446,  507,  959,  959,
      689,  138,  197,  324,  959,    0,  959,  382,  390,  249,
      959,  697,  395,  959,  406,    0,    0,  959,  419,  450,
      277,  336,  455,  500,  518,  285,  415,  548,  520,    0,
      460,  522,  959,  959,  670,  648,  641,  645,  639,  640,
      626,  623,  616,  630,  618,  603,  590,  603,  598,    0,

       89,  592,  587,    0,  563,  561,  550,  547,  532,  531,
      528,  527,  527,  506,  507,  514,    0,    0,  513,  505,
      504,  547,  546,  208,  584,  608,  474,  526,  576,  606,
        0,  611,  636,  641,  582,  600,  959,  281,  658,  959,
      649,  284,  139,  676,    0,  959,  694,  556,    0,    0,
      700,  602,  705,  318,  394,  179,  709,    0,  714,    0,
      716,  959,  467,  469,  463,    0,  464,  453,  460,  451,
        0,  445,  452,  445,  431,  443,  430,  428,    0,  413,
      420,  411,  402,  399,  407,  397,  404,    0,  390,    0,
        0,  396,  387,  425,  417,  415,  733,  740,  764,  769,

      482,  186,  780,  794,  609,  203,  359,  357,    0,    0,
        0,  344,  350,  344,  322,    0,  319,  311,  322,  308,
      307,  321,  310,  316,    0,  289,  283,    0,    0,  333,
      799,  959,  829,    0,  280,  263,  263,  248,  255,    0,
      251,  227,  238,    0,    0,    0,  213,    0,  959,    0,
      211,    0,    0,  196,  197,    0,    0,  178,    0,  172,
      176,  157,  131,    0,  123,    0,  119,   77,    0,  959,
      874,  883,  890,  899,  908,  914,  916,  918,  924,  933,
      938,  943,  946,  951
    } ;

static const flex_int16_t yy_def[385] =
    {   0,
      370,    1,  371,  371,  370,  370,  370,  370,  370,  370,
      372,  373,  370,  370,  374,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  372,
      372,  370,  372,  373,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      375,  370,  370,   25,   84,  370,  370,  370,  370,  376,
      370,  370,  377,   25,  370,  370,  370,  370,  370,  370,

      370,  370,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  370,  370,  370,
      370,  370,  370,  372,  372,  372,  372,  372,  370,  370,
      370,  370,  370,  370,  370,   79,  370,  370,  370,  375,
      370,  370,   83,  370,  370,   84,   84,  370,  370,  370,
      370,  370,  370,  370,  378,   84,  370,  370,  379,   94,
      370,   94,  370,  370,  370,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  370,  380,  380,  372,  372,  370,  370,  370,  370,
      163,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  381,  382,  378,  244,  370,  370,  244,  176,  176,
      370,  370,  370,  370,  383,  384,  379,  257,  257,  182,
      370,  370,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  380,  380,  380,  370,  370,  370,  370,

      381,  301,  370,  370,  383,  305,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  380,
      370,  370,  370,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  370,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,    0,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370
    } ;

static const flex_int16_t yy_nxt[1033] =
    {   0,
        6,    6,    7,    8,    7,    9,    7,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   25,   25,   25,   26,   27,   28,   29,
       30,   31,   12,   12,   12,   12,   12,   12,   12,   12,
       32,    6,   33,   34,   12,   35,   36,   37,   38,   39,
       40,   12,   12,   41,   12,   42,   12,   43,   12,   44,
       45,   46,   47,   12,   48,   49,   12,   50,   12,   51,
       52,   53,   54,   56,   56,   61,   61,   61,   61,   61,
       66,   73,   62,   57,   57,   75,   61,  122,   69,   69,
       69,   69,   69,  161,   74,  162,   76,   77,   67,   70,

       78,  123,   79,   79,   79,   79,   79,   80,   97,   98,
      100,  101,   81,  118,  104,   63,  105,  107,  112,  119,
      120,   82,  128,  106,  108,  369,  114,  109,   71,  113,
      110,  124,  129,  130,  115,   61,  116,  131,  132,  117,
      138,  151,  125,  134,  276,  126,  133,  277,   69,   83,
      149,   84,   84,   84,   84,   85,  135,  171,  171,   85,
       85,   85,   85,   86,   87,   88,   87,   89,  368,   90,
      177,  177,  184,  185,   91,  370,   92,  247,   87,   88,
       87,  139,  170,   61,   61,   61,   61,   61,  214,  216,
      142,  367,  366,  217,   61,  215,   93,   83,  247,   94,

       94,   94,   94,   94,  222,  223,  222,  224,  222,  149,
      365,  296,   87,   88,   87,   89,  295,  247,  227,  227,
      227,  227,   95,   63,  370,  364,   87,   88,   87,   61,
       61,   61,   61,   61,  363,  362,  142,  151,  247,  152,
       61,  370,   70,   61,  361,  370,  149,  166,  167,  166,
      166,   85,  161,  360,  162,  153,  153,  153,  154,  172,
      359,  172,  370,  168,  173,  173,  173,  173,  173,   63,
      169,  358,  176,  176,  176,  176,   85,  180,  180,  180,
      180,  180,  182,  182,  182,  182,  182,  357,  356,   61,
       61,   61,  144,   61,  145,   91,  355,  146,  235,  236,

      181,   61,  235,  235,  354,   95,  249,  250,  249,  249,
      147,  147,  147,  148,  237,  353,   61,   61,   61,   61,
       61,  238,  247,  142,  352,  238,  351,   61,  302,  251,
       63,   61,   61,  144,   61,   61,  149,  350,  142,  252,
      252,  349,   61,  247,  348,  228,  228,  228,  228,  347,
       61,  156,  156,  156,  156,  156,   63,  173,  173,  173,
      173,  173,  254,  346,  157,  158,  157,  345,  344,  343,
      342,   63,  341,  340,  159,  339,   61,  338,  157,  158,
      157,  163,  163,  163,  163,  163,   61,   61,   61,   61,
       61,   61,  337,  142,  164,  165,  164,   61,  229,  316,

      229,  336,  335,  230,  230,  230,  230,  230,  164,  165,
      164,  156,  156,  156,  156,  156,  231,  231,  231,  231,
      231,  334,  233,  295,  233,  330,   63,  234,  234,  234,
      234,  234,  247,  295,  159,  329,  252,  253,  306,  232,
      166,  166,  166,  166,   85,  328,   61,   61,   61,   61,
       61,   61,  237,  247,  142,  327,  326,  325,   61,  254,
      324,  266,  323,  169,  322,  321,  320,  225,  225,  225,
      225,   85,   85,   85,   85,   85,  239,  239,  239,  239,
      239,  180,  180,  180,  180,  180,  149,   63,  319,  240,
      318,  240,  317,  316,  170,  228,  228,  228,  228,  241,

      315,  290,  314,  240,  181,  240,  313,   61,   61,   61,
       61,   61,   61,  312,  311,  142,  310,  309,  308,   61,
      247,  242,  242,  242,  242,  242,  302,  307,  226,  226,
      226,  226,  242,  242,  242,  242,  242,  243,  149,  256,
      245,  247,  258,  260,  260,  260,  260,  260,   63,  222,
      223,  222,  224,  222,  295,  246,  247,  246,  247,  293,
      292,  291,  248,  290,  259,  289,  261,  288,   61,  255,
      255,  255,  255,  255,  287,  370,  286,  247,  244,  247,
      255,  255,  255,  255,  255,   61,   61,   61,   61,   61,
      285,  284,  142,  370,  370,  283,   61,  230,  230,  230,

      230,  230,  282,  235,  236,  226,  226,  226,  226,   61,
       61,   61,   61,   61,  281,  370,  142,  280,  279,  237,
       61,  235,  236,  252,  253,   63,  238,  297,  297,  297,
      297,  297,  231,  231,  231,  231,  231,  237,  266,  237,
      157,  278,  157,  275,  238,   61,  254,  247,  274,   63,
      298,  273,  272,  306,  157,  232,  157,  234,  234,  234,
      234,  234,  299,  299,  299,  299,  299,  271,  247,   61,
      239,  239,  239,  239,  239,  164,  270,  164,  269,  239,
      239,  239,  239,  239,  268,  300,  266,  267,  266,  164,
      265,  164,  240,  241,  240,  243,  264,  263,  245,  262,

      161,  149,  241,  221,  220,  219,  240,  218,  240,  213,
      303,  212,  303,  246,  247,  304,  304,  304,  304,  304,
      248,  249,  249,  249,  249,   85,  252,  253,  256,  211,
      210,  258,  209,  370,  208,  247,  257,  260,  260,  260,
      260,  260,  237,  207,  251,  206,  246,  247,  205,  254,
      204,  370,  370,  259,  297,  297,  297,  297,  297,  203,
      261,  297,  297,  297,  297,  297,  202,  157,  247,  157,
      201,  200,  199,  370,  198,  197,  196,  298,  195,  194,
      193,  157,  192,  157,  298,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  191,  190,  189,  164,  188,

      164,  304,  304,  304,  304,  304,  187,  186,  300,  183,
      178,  174,  164,  300,  164,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  155,  149,  150,  332,  149,
      332,  143,  141,  332,  140,  332,  137,  136,  333,  127,
      121,  111,  332,  333,  332,  103,  102,  332,   99,  332,
      331,  331,  331,  331,  331,   96,   72,   65,   59,   58,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  333,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   64,  370,   64,   64,   64,  370,   64,   68,

       68,   68,   68,   68,   68,   68,   68,   68,  160,  370,
      160,  160,  160,  160,  160,  160,  160,  175,  175,  179,
      179,  244,  244,  244,  244,  370,  244,  257,  257,  257,
      257,  370,  257,  294,  294,  294,  294,  294,  294,  294,
      370,  294,  301,  370,  301,  370,  301,  242,  370,  242,
      305,  370,  305,  370,  305,  255,  370,  255,    5,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370
    } ;

static const flex_int16_t yy_chk[1033] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   11,   11,   11,   11,   11,
       14,   19,   11,    3,    4,   21,   11,   43,   15,   15,
       15,   15,   15,   81,   19,   81,   21,   21,   14,   15,

       22,   43,   22,   22,   22,   22,   22,   23,   28,   28,
       30,   30,   23,   41,   36,   11,   36,   37,   39,   41,
       41,   23,   46,   36,   37,  368,   40,   37,   15,   39,
       37,   44,   46,   46,   40,   11,   40,   46,   47,   40,
       52,  152,   44,   48,  201,   44,   47,  201,   15,   24,
      152,   24,   24,   24,   24,   24,   48,   86,   86,   85,
       85,   85,   85,   24,   24,   24,   24,   24,  367,   24,
       92,   92,  101,  101,   24,   85,   24,  243,   24,   24,
       24,   52,   85,   60,   60,   60,   60,   60,  132,  133,
       60,  365,  363,  133,   60,  132,   24,   25,  243,   25,

       25,   25,   25,   25,  143,  143,  143,  143,  143,  153,
      362,  224,   25,   25,   25,   25,  224,  256,  153,  153,
      153,  153,   25,   60,  302,  361,   25,   25,   25,   61,
       61,   61,   61,   61,  360,  358,   61,   71,  256,   71,
       61,  306,   71,   60,  355,  302,   71,   84,   84,   84,
       84,   84,  160,  354,  160,   71,   71,   71,   71,   88,
      351,   88,  306,   84,   88,   88,   88,   88,   88,   61,
       84,  347,   91,   91,   91,   91,   91,   94,   94,   94,
       94,   94,   95,   95,   95,   95,   95,  343,  342,   61,
       63,   63,   63,   63,   63,   91,  341,   63,  171,  171,

       94,   63,  238,  238,  339,   95,  176,  176,  176,  176,
       63,   63,   63,   63,  171,  338,  144,  144,  144,  144,
      144,  171,  242,  144,  337,  238,  336,  144,  242,  176,
       63,  145,  145,  145,  145,  145,  154,  335,  145,  254,
      254,  330,  145,  242,  327,  154,  154,  154,  154,  326,
       63,   79,   79,   79,   79,   79,  144,  172,  172,  172,
      172,  172,  254,  324,   79,   79,   79,  323,  322,  321,
      320,  145,  319,  318,   79,  317,  144,  315,   79,   79,
       79,   83,   83,   83,   83,   83,  146,  146,  146,  146,
      146,  145,  314,  146,   83,   83,   83,  146,  158,  313,

      158,  312,  308,  158,  158,  158,  158,  158,   83,   83,
       83,  159,  159,  159,  159,  159,  163,  163,  163,  163,
      163,  307,  165,  296,  165,  295,  146,  165,  165,  165,
      165,  165,  255,  294,  159,  293,  177,  177,  255,  163,
      169,  169,  169,  169,  169,  292,  146,  147,  147,  147,
      147,  147,  177,  255,  147,  289,  287,  286,  147,  177,
      285,  284,  283,  169,  282,  281,  280,  147,  147,  147,
      147,  170,  170,  170,  170,  170,  173,  173,  173,  173,
      173,  181,  181,  181,  181,  181,  227,  147,  278,  173,
      277,  173,  276,  275,  170,  227,  227,  227,  227,  173,

      274,  273,  272,  173,  181,  173,  270,  147,  148,  148,
      148,  148,  148,  269,  268,  148,  267,  265,  264,  148,
      301,  174,  174,  174,  174,  174,  301,  263,  148,  148,
      148,  148,  174,  174,  174,  174,  174,  175,  228,  179,
      175,  301,  179,  182,  182,  182,  182,  182,  148,  222,
      222,  222,  222,  222,  223,  175,  175,  179,  179,  221,
      220,  219,  175,  216,  179,  215,  182,  214,  148,  178,
      178,  178,  178,  178,  213,  248,  212,  175,  248,  179,
      178,  178,  178,  178,  178,  225,  225,  225,  225,  225,
      211,  210,  225,  248,  248,  209,  225,  229,  229,  229,

      229,  229,  208,  235,  235,  225,  225,  225,  225,  226,
      226,  226,  226,  226,  207,  248,  226,  206,  205,  235,
      226,  236,  236,  252,  252,  225,  235,  230,  230,  230,
      230,  230,  232,  232,  232,  232,  232,  236,  203,  252,
      230,  202,  230,  199,  236,  225,  252,  305,  198,  226,
      230,  197,  196,  305,  230,  232,  230,  233,  233,  233,
      233,  233,  234,  234,  234,  234,  234,  195,  305,  226,
      241,  241,  241,  241,  241,  234,  194,  234,  193,  239,
      239,  239,  239,  239,  192,  234,  191,  190,  189,  234,
      188,  234,  239,  241,  239,  244,  187,  186,  244,  185,

      162,  151,  239,  137,  136,  135,  239,  134,  239,  131,
      247,  130,  247,  244,  244,  247,  247,  247,  247,  247,
      244,  251,  251,  251,  251,  251,  253,  253,  257,  129,
      128,  257,  127,  259,  126,  244,  259,  261,  261,  261,
      261,  261,  253,  125,  251,  124,  257,  257,  123,  253,
      122,  259,  259,  257,  297,  297,  297,  297,  297,  121,
      261,  298,  298,  298,  298,  298,  120,  297,  257,  297,
      119,  117,  116,  259,  115,  114,  113,  297,  112,  111,
      110,  297,  109,  297,  298,  299,  299,  299,  299,  299,
      300,  300,  300,  300,  300,  108,  107,  106,  299,  105,

      299,  303,  303,  303,  303,  303,  104,  103,  299,   97,
       93,   90,  299,  300,  299,  304,  304,  304,  304,  304,
      331,  331,  331,  331,  331,   78,   70,   69,  304,   68,
      304,   62,   57,  331,   56,  331,   50,   49,  304,   45,
       42,   38,  304,  331,  304,   35,   34,  331,   29,  331,
      333,  333,  333,  333,  333,   26,   18,   13,   10,    9,
        5,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  333,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  373,    0,  373,  373,  373,    0,  373,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  375,    0,
      375,  375,  375,  375,  375,  375,  375,  376,  376,  377,
      377,  378,  378,  378,  378,    0,  378,  379,  379,  379,
      379,    0,  379,  380,  380,  380,  380,  380,  380,  380,
        0,  380,  381,    0,  381,    0,  381,  382,    0,  382,
      383,    0,  383,    0,  383,  384,    0,  384,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[98] =
    {   0,
0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include<bits/stdc++.h>
using namespace std;
#include "parser.tab.h"
extern int leaf_number;
extern fstream fout;
extern stack<int> st;
string s;

#line 832 "lex.yy.c"

#line 834 "lex.yy.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 150 "lexer.l"


#line 1055 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 371 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 959 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 152 "lexer.l"
{BEGIN comment;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 153 "lexer.l"
{BEGIN 0;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 154 "lexer.l"
//
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 156 "lexer.l"
{}        
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 157 "lexer.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 158 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return TRIPLE_DOT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 159 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return AMPERSAND;} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 160 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return AMPERSAND_AMPERSAND;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 161 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return AMPERSAND_EQUALS;} 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 162 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return ARROW_RIGHT;}  
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 163 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return BAR;}  
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 164 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return BAR_BAR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 165 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return BAR_EQUALS;}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 166 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return CHARACTER_LITERAL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 167 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return COLON;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 168 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return COMMA;}   
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 169 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return DOT;}   
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 170 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return DOUBLE_COLON;} 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 171 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return EQUALS;} 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 172 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return EQUALS_EQUALS;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 173 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return EXCLAIM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 174 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return EXCLAIM_EQUALS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 175 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return FLOATINGPOINT_LITERAL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 176 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return GREATER_THAN;} 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 177 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return GREATER_THAN_EQUALS;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 178 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return GREATER_THAN_GREATER_THAN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 179 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return GREATER_THAN_GREATER_THAN_EQUALS;} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 180 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return GREATER_THAN_GREATER_THAN_GREATER_THAN;} 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 181 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return GREATER_THAN_GREATER_THAN_GREATER_THAN_EQUALS;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 182 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return LEFT_CURLY_BRACE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 183 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return LEFT_PARANTHESIS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 184 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return LEFT_SQUARE_BRACE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 185 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return LESS_THAN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 186 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return LESS_THAN_EQUALS;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 187 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return LESS_THAN_LESS_THAN;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 188 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return LESS_THAN_LESS_THAN_EQUALS;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 189 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return MINUS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 190 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return MINUS_EQUALS;}  
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 191 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return MINUS_MINUS;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 192 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return PERCENT;} 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 193 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return PERCENT_EQUALS;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 194 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return PLUS;}           
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 195 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return PLUS_EQUALS;}  
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 196 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return PLUS_PLUS;}   
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 197 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return POWER;}   
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 198 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return POWER_EQUALS;}   
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 199 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return QUESTION;}   
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 200 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return RIGHT_CURLY_BRACE;}   
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 201 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return RIGHT_PARANTHESIS;}   
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 202 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return RIGHT_SQUARE_BRACE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 203 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return SEMI_COLON;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 204 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return SLASH;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 205 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return SLASH_EQUALS;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 206 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return STAR;}    
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 207 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return STAR_EQUALS;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 208 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return YIELD;}    
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 209 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return WHILE;}    
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 210 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return VOID;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 211 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return VAR;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 212 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return TRY;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 213 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return TILDA;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 214 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return INTEGER_LITERAL;}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 215 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return TEXTBLOCK;}    
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 216 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return THROWS;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 217 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return THROW;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 218 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return THIS;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 219 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return SYNCHRONIZED;}    
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 220 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return SUPER;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 221 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return STATIC;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 222 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return RETURN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 223 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return PUBLIC;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 224 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return PRIVATE;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 225 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return PERMITS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 226 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return NULL_LITERAL;}    
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 227 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return NEW;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 228 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return INTERFACE;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 229 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return INTEGRAL_TYPE;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 230 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return IMPORT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 231 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return IMPLEMENTS;}    
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 232 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return IF;}    
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 233 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return FOR;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 234 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return FLOAT_POINT_TYPE;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 235 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return FINALLY;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 236 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return FINAL;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 237 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return EXTENDS;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 238 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return ELSE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 239 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return CONTINUE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 240 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return CLASS;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 241 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return CATCH;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 242 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return BREAK;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 243 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return BOOLEAN_TYPE;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 244 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return BOOLEAN_LITERAL;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 245 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return ASSERT;}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 246 "lexer.l"
{fout<<"t"<<leaf_number<<"[label="<<yytext<<"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return STRING_LITERAL;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 247 "lexer.l"
{fout<<"t"<<leaf_number<<"[label=\""<<yytext<<"\"]"<<endl; if(leaf_number) st.push(1-leaf_number);  leaf_number++; return IDENTIFIER;}
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 248 "lexer.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
#line 249 "lexer.l"
{st.push(1-leaf_number); yyterminate();}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 253 "lexer.l"
ECHO;
	YY_BREAK
#line 1618 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 371 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 371 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 370);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 253 "lexer.l"


int yywrap() {
    return 1;
}
