
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[381] =
    {   0,
        0,    0,    0,    0,   99,   98,    4,    5,    5,   21,
       98,   96,   41,    7,   98,   31,   50,   55,   43,   16,
       37,   17,   53,   63,   63,   15,   52,   33,   19,   24,
       48,   96,   32,   51,   46,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   30,   11,   49,   62,    3,    3,    3,    5,   22,
        0,    0,   95,    0,   96,   42,    8,    9,    0,    0,
        0,    0,   56,   45,   44,   39,   38,   10,    0,   23,
        1,   97,   54,   23,   63,    0,    0,   23,    0,   63,
        0,    0,    0,    0,   63,    0,   18,   35,   34,   20,

       25,   26,   96,   47,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   80,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       13,   12,    3,    2,   95,    0,    0,    0,   95,    0,
        0,   14,   14,    0,    0,    0,    0,    6,   23,   23,
        0,    0,   97,   97,   97,   23,   23,    0,   63,   63,
       63,    0,    0,   63,    0,   23,    0,   63,   63,   63,
        0,   63,   63,    0,   63,   36,   27,   28,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,

       96,   96,   96,   81,   96,   77,   96,   75,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       61,   60,   96,   96,   96,    0,    0,    0,    0,    0,
        0,    0,    0,   23,   23,    0,    0,   23,   63,   63,
       63,    0,   23,   23,    0,    0,    0,   63,   63,   63,
        0,    0,   63,   63,    0,   63,   63,    0,    0,    0,
       63,   63,    0,   63,    0,   29,   96,   96,   96,   96,
       77,   96,   96,   96,   96,   86,   96,   96,   96,   96,
       96,   96,   96,   74,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   92,   59,   96,   96,    0,    0,

        0,   23,    0,   23,    0,    0,    0,    0,   23,    0,
        0,   96,   96,   96,   90,   89,   88,   96,   96,   96,
       84,   82,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   68,   96,   66,   58,   57,    0,   23,   23,    0,
       94,   93,   96,   96,   96,   96,   96,   78,   96,   96,
       96,   96,   71,   70,   69,   96,   65,   64,   91,   96,
       85,   83,   96,   96,   40,   73,   72,   96,   87,   96,
       96,   96,   96,   76,   96,   79,   96,   96,   67,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        1,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,    9,    1,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   25,   25,   25,   25,   26,   26,   27,   28,   29,
       30,   31,   32,    1,   33,   34,   33,   35,   36,   37,
       10,   10,   10,   10,   10,   38,   10,   10,   10,   39,
       10,   10,   40,   10,   10,   10,   10,   41,   10,   10,
       42,   43,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   10,   56,   57,   58,   59,
       60,   61,   10,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   71,   72,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        1,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    5,    5,    5,    5,    5,    6,    5,    3,
        3,    1,    7,    1,    1,    8,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        5,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[393] =
    {   0,
        0,    0,   69,   70,  853, 1041, 1041, 1041,  848,  820,
       75,    0,  819,   70,   88, 1041, 1041,  818,   66, 1041,
       68,   82,   93,  132,  181,  820, 1041,   81,  815,   82,
     1041,  780, 1041, 1041,  813,  778,   55,   72,  779,   59,
       73,   82,  778,   38,   74,  770,   81,   99,  100,  766,
      763, 1041,   65, 1041, 1041, 1041,  812,  794, 1041, 1041,
      183,  232,  805,  294,    0, 1041, 1041, 1041,  800,  798,
      795,  189, 1041, 1041, 1041, 1041, 1041, 1041,  787,  336,
     1041,  138, 1041,  226,  233,  242,  126, 1041,  267, 1041,
      288,  198,  140,  306,  322,  328, 1041,  776, 1041, 1041,

     1041,  134,  743, 1041,  739,  741,  749,  728,  726,  739,
      737,  714,  706,  693,  690,  695,  692,  680,  677,    0,
      674,  669,  671,  662,  667,  673,  657,  663,  655,  638,
      639,  651,  636,  636,  632,  106,  631,  637,  635,  619,
     1041, 1041, 1041, 1041, 1041,  360,  387,  399,  411,  473,
      535, 1041, 1041,  656,  168,  356,  409, 1041,    0, 1041,
      421,  403,  170, 1041,  653,  577, 1041,  434,    0,    0,
     1041,  441,  446,  361,  477,  482,  487,  507,  527,  372,
      557,  549,    0,  539,  593, 1041, 1041,  620,  594,  597,
      589,  598,  575,  576,  562,  559,  556,  563,  558,  546,

      533,  539,  537,    0,  134,  526,  523,    0,  518,  515,
      512,  500,  499,  490,  492,  483,  492,  493,  475,  482,
        0,    0,  481,  472,  469,  601,  516,  206,  638,  662,
      608,  505,  612,  654,    0,  661,  630,  686,  636,  650,
     1041,  207,  691, 1041,  722,  208,  138,  711,    0, 1041,
      736,  741,    0,    0,  757,  747,  766,  259,  248,  288,
      771,    0,  800,    0,  773, 1041,  456,  452,  443,  437,
        0,  437,  427,  434,  431,    0,  426,  433,  426,  417,
      429,  411,  399,    0,  408,  397,  401,  386,  377,  373,
      381,  373,  369,  354,    0,    0,  368,  361,  400,  397,

      389,  805,  836,  841,  846,  528,  872,  877,  888,  681,
      919,  344,  321,  330,    0,    0,    0,  317,  324,  320,
      299,    0,  297,  274,  284,  282,  270,  269,  271,  256,
      257,    0,  242,  239,    0,    0,  292,  924, 1041,  905,
        0,    0,  226,  218,  211,  204,  221,    0,  223,  217,
      197,  192,    0,    0,    0,  182,    0, 1041,    0,  189,
        0,    0,  180,  179,    0,    0,    0,  166,    0,  145,
      157,  142,  127,    0,  109,    0,  108,   93,    0, 1041,
      976,  984,  990,  998, 1006, 1011, 1016, 1024, 1028,  117,
     1032,   92

    } ;

static const flex_int16_t yy_def[393] =
    {   0,
      380,    1,  381,  381,  380,  380,  380,  380,  380,  380,
      382,  383,  380,  380,  384,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  383,  380,  380,  380,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      382,  382,  380,  382,  383,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  385,  380,  380,   25,   85,  380,  380,  380,  380,
      380,  380,  380,  380,   25,  380,  380,  380,  380,  380,

      380,  380,  383,  380,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      380,  380,  380,  380,  380,  380,  382,  382,  382,  382,
      382,  380,  380,  380,  380,  380,  380,  380,   80,  380,
      380,  380,  385,  380,  380,  380,  380,  380,   85,   85,
      380,  380,  380,  380,  380,  380,  380,  386,   85,  380,
      380,  387,   95,  380,   95,  380,  380,  380,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  380,  388,  388,  382,  382,
      380,  380,  380,  380,  166,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  389,  390,  386,  248,  380,
      380,  380,  179,  179,  380,  380,  380,  380,  391,  392,
      387,  261,  380,  185,  380,  380,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  388,  388,

      388,  380,  380,  380,  380,  389,  380,  380,  380,  391,
      380,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  388,  380,  380,  380,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  380,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,    0,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380

    } ;

static const flex_int16_t yy_nxt[1116] =
    {   0,
        6,    6,    7,    8,    7,    9,    7,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   25,   25,   25,   26,   27,   28,   29,
       30,   31,   12,   12,   12,   12,   12,   12,   12,   32,
       12,   33,    6,   34,   35,   12,   36,   37,   38,   39,
       40,   41,   12,   12,   42,   12,   43,   12,   44,   12,
       45,   46,   47,   48,   12,   49,   50,   12,   51,   12,
       52,   53,   54,   55,   57,   57,   62,   62,   62,   62,
       62,   67,   74,   63,   58,   58,   76,   62,  124,   70,
       70,   70,   70,   70,  141,   75,  259,   77,   78,   68,

       71,   79,  125,   80,   80,   80,   80,   80,   81,   98,
       99,  101,  102,   82,  106,  114,  107,   64,  109,  116,
      126,  246,   83,  108,  127,  110,  115,  117,  111,  118,
       72,  112,  119,  120,  131,  128,  142,   62,  129,  121,
      122,  164,  379,  165,  132,  133,  137,  174,  174,  134,
       70,   84,  135,   85,   85,   85,   85,   86,  378,  138,
      136,  180,  180,  187,  188,   87,   88,   89,   88,   90,
      220,  154,   91,  164,  221,  165,  251,   92,  377,   93,
      152,   88,   89,   88,   62,   62,   62,   62,   62,  376,
      281,  145,  154,  282,  155,   62,  375,   71,  251,   94,

       84,  152,   95,   95,   95,   95,   95,  374,  373,  301,
      156,  156,  156,  157,  300,   88,   89,   88,   90,  179,
      179,  179,  179,   86,  372,   64,   96,  371,  239,  239,
       88,   89,   88,   62,   62,   62,   62,   62,  370,  369,
      145,  368,  367,   92,   62,   62,  251,  166,  166,  166,
      166,  166,  242,  307,  169,  170,  169,  169,   86,  366,
      167,  168,  167,   86,   86,   86,   86,  365,  251,  364,
      171,  363,  362,  361,   64,  167,  168,  167,  172,  380,
      256,  256,  360,  175,  359,  175,  251,  173,  176,  176,
      176,  176,  176,  311,   62,   62,   62,  147,   62,  148,

      358,  357,  149,  356,  258,  355,   62,  177,  251,  178,
      178,  178,  178,  178,  354,  150,  150,  150,  151,  353,
      178,  178,  178,  178,  178,  181,  251,  182,  182,  182,
      182,  182,  352,  351,  350,  349,   64,  348,  182,  182,
      182,  182,  182,  183,  183,  183,  183,  183,  251,  185,
      185,  185,  185,  185,  347,  346,   62,  159,  159,  159,
      159,  159,  226,  227,  226,  228,  226,  184,  152,  345,
      160,  161,  160,   96,  322,  344,  343,  231,  231,  231,
      231,  162,  239,  240,  342,  160,  161,  160,   62,   62,
       62,   62,   62,  256,  257,  145,  341,  300,  241,   62,

       62,   62,  147,   62,   62,  337,  242,  145,  300,  241,
      336,   62,   62,   62,   62,   62,   62,  258,  335,  145,
      334,  152,  333,   62,  159,  159,  159,  159,  159,   64,
      232,  232,  232,  232,  332,  331,  271,  233,  330,  233,
      329,   64,  234,  234,  234,  234,  234,  328,  162,   62,
      237,  327,  237,   64,  326,  238,  238,  238,  238,  238,
      325,   62,  169,  169,  169,  169,   86,   86,   86,   86,
       86,   86,  324,   62,   62,   62,   62,   62,   62,  323,
      322,  145,  321,  295,  320,   62,  172,  319,  318,  317,
      316,  173,  315,  314,  229,  229,  229,  229,  176,  176,

      176,  176,  176,  243,  243,  243,  243,  243,  246,  246,
      246,  246,  246,  313,  312,   64,  244,  152,  244,  246,
      246,  246,  246,  246,  300,  298,  247,  245,  297,  249,
      296,  244,  295,  244,  294,   62,   62,   62,   62,   62,
       62,  293,  292,  145,  250,  251,  291,   62,  253,  254,
      253,  253,  252,  290,  289,  288,  230,  230,  230,  230,
      183,  183,  183,  183,  183,  287,  251,  251,  260,  286,
      285,  262,  255,  307,  284,  271,  283,   64,  259,  259,
      259,  259,  259,  280,  184,  279,  250,  251,  251,  259,
      259,  259,  259,  259,  263,  278,  277,   62,  235,  235,

      235,  235,  235,  226,  227,  226,  228,  226,  276,  251,
      275,  167,  168,  167,  264,  264,  264,  264,  264,  274,
      152,  273,  236,  271,  272,  271,  167,  168,  167,  232,
      232,  232,  232,  234,  234,  234,  234,  234,  265,   62,
       62,   62,   62,   62,  270,  269,  145,  268,  267,  266,
       62,  238,  238,  238,  238,  238,  164,  239,  240,  230,
      230,  230,  230,   62,   62,   62,   62,   62,  152,  225,
      145,  239,  240,  241,   62,  302,  302,  302,  302,  302,
       64,  242,  235,  235,  235,  235,  235,  241,  160,  224,
      160,  223,  222,  219,  218,  242,  217,  216,  215,  303,

       62,  214,  213,  160,   64,  160,  236,  304,  304,  304,
      304,  304,  243,  243,  243,  243,  243,  212,  211,  251,
      167,  210,  167,  209,   62,  244,  311,  244,  208,  207,
      247,  305,  206,  249,  205,  167,  245,  167,  204,  203,
      244,  251,  244,  243,  243,  243,  243,  243,  250,  251,
      202,  201,  308,  200,  308,  199,  252,  309,  309,  309,
      309,  309,  248,  248,  248,  248,  248,  245,  256,  257,
      198,  251,  197,  248,  248,  248,  248,  248,  253,  253,
      253,  253,   86,  196,  241,  195,  252,  256,  257,  194,
      260,  193,  258,  262,  264,  264,  264,  264,  264,  192,

      191,  190,  255,  241,  189,  186,  158,  152,  250,  251,
      153,  258,  152,  146,  144,  143,  263,  140,  265,  139,
      130,  261,  261,  261,  261,  261,  302,  302,  302,  302,
      302,  251,  261,  261,  261,  261,  261,  123,  113,  160,
      105,  160,  104,  103,  100,  263,   97,   73,   66,   60,
      303,   59,  380,  380,  160,  380,  160,  302,  302,  302,
      302,  302,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  380,  380,  380,  167,  380,  167,  380,  380,
      380,  303,  380,  380,  380,  380,  305,  380,  380,  380,
      167,  305,  167,  306,  306,  306,  306,  306,  309,  309,

      309,  309,  309,  380,  306,  306,  306,  306,  306,  338,
      338,  338,  338,  338,  380,  380,  380,  307,  380,  380,
      380,  380,  339,  380,  339,  380,  338,  338,  338,  338,
      338,  380,  380,  340,  380,  380,  380,  339,  380,  339,
      310,  310,  310,  310,  310,  338,  338,  338,  338,  338,
      340,  310,  310,  310,  310,  310,  380,  380,  339,  380,
      339,  380,  380,  380,  311,  380,  380,  380,  380,  340,
      380,  380,  380,  339,  380,  339,   56,   56,   56,   56,
       56,   56,   56,   56,   61,   61,   61,   61,   61,   61,
       61,   61,   65,  380,   65,   65,  380,   65,   69,   69,

       69,   69,   69,   69,   69,   69,  163,  380,  163,  163,
      163,  163,  163,  163,  248,  248,  248,  380,  248,  261,
      261,  261,  380,  261,  299,  299,  299,  299,  299,  299,
      380,  299,  306,  380,  380,  306,  310,  380,  380,  310,
        5,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380
    } ;

static const flex_int16_t yy_chk[1116] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   11,   11,   11,   11,
       11,   14,   19,   11,    3,    4,   21,   11,   44,   15,
       15,   15,   15,   15,   53,   19,  392,   21,   21,   14,

       15,   22,   44,   22,   22,   22,   22,   22,   23,   28,
       28,   30,   30,   23,   37,   40,   37,   11,   38,   41,
       45,  390,   23,   37,   45,   38,   40,   41,   38,   41,
       15,   38,   41,   42,   47,   45,   53,   11,   45,   42,
       42,   82,  378,   82,   47,   47,   49,   87,   87,   47,
       15,   24,   48,   24,   24,   24,   24,   24,  377,   49,
       48,   93,   93,  102,  102,   24,   24,   24,   24,   24,
      136,  155,   24,  163,  136,  163,  247,   24,  375,   24,
      155,   24,   24,   24,   61,   61,   61,   61,   61,  373,
      205,   61,   72,  205,   72,   61,  372,   72,  247,   24,

       25,   72,   25,   25,   25,   25,   25,  371,  370,  228,
       72,   72,   72,   72,  228,   25,   25,   25,   25,   92,
       92,   92,   92,   92,  368,   61,   25,  364,  242,  242,
       25,   25,   25,   62,   62,   62,   62,   62,  363,  360,
       62,  356,  352,   92,   62,   61,  246,   84,   84,   84,
       84,   84,  242,  246,   85,   85,   85,   85,   85,  351,
       84,   84,   84,   86,   86,   86,   86,  350,  246,  349,
       85,  347,  346,  345,   62,   84,   84,   84,   85,   86,
      258,  258,  344,   89,  343,   89,  259,   86,   89,   89,
       89,   89,   89,  259,   62,   64,   64,   64,   64,   64,

      337,  334,   64,  333,  258,  331,   64,   91,  259,   91,
       91,   91,   91,   91,  330,   64,   64,   64,   64,  329,
       91,   91,   91,   91,   91,   94,  260,   94,   94,   94,
       94,   94,  328,  327,  326,  325,   64,  324,   94,   94,
       94,   94,   94,   95,   95,   95,   95,   95,  260,   96,
       96,   96,   96,   96,  323,  321,   64,   80,   80,   80,
       80,   80,  146,  146,  146,  146,  146,   95,  156,  320,
       80,   80,   80,   96,  319,  318,  314,  156,  156,  156,
      156,   80,  174,  174,  313,   80,   80,   80,  147,  147,
      147,  147,  147,  180,  180,  147,  312,  301,  174,  147,

      148,  148,  148,  148,  148,  300,  174,  148,  299,  180,
      298,  148,  149,  149,  149,  149,  149,  180,  297,  149,
      294,  157,  293,  149,  162,  162,  162,  162,  162,  147,
      157,  157,  157,  157,  292,  291,  290,  161,  289,  161,
      288,  148,  161,  161,  161,  161,  161,  287,  162,  147,
      168,  286,  168,  149,  285,  168,  168,  168,  168,  168,
      283,  148,  172,  172,  172,  172,  172,  173,  173,  173,
      173,  173,  282,  149,  150,  150,  150,  150,  150,  281,
      280,  150,  279,  278,  277,  150,  172,  275,  274,  273,
      272,  173,  270,  269,  150,  150,  150,  150,  175,  175,

      175,  175,  175,  176,  176,  176,  176,  176,  177,  177,
      177,  177,  177,  268,  267,  150,  176,  232,  176,  177,
      177,  177,  177,  177,  227,  225,  178,  176,  224,  178,
      223,  176,  220,  176,  219,  150,  151,  151,  151,  151,
      151,  218,  217,  151,  178,  178,  216,  151,  179,  179,
      179,  179,  178,  215,  214,  213,  151,  151,  151,  151,
      184,  184,  184,  184,  184,  212,  306,  178,  182,  211,
      210,  182,  179,  306,  209,  207,  206,  151,  181,  181,
      181,  181,  181,  203,  184,  202,  182,  182,  306,  181,
      181,  181,  181,  181,  182,  201,  200,  151,  166,  166,

      166,  166,  166,  226,  226,  226,  226,  226,  199,  182,
      198,  166,  166,  166,  185,  185,  185,  185,  185,  197,
      231,  196,  166,  195,  194,  193,  166,  166,  166,  231,
      231,  231,  231,  233,  233,  233,  233,  233,  185,  229,
      229,  229,  229,  229,  192,  191,  229,  190,  189,  188,
      229,  237,  237,  237,  237,  237,  165,  239,  239,  229,
      229,  229,  229,  230,  230,  230,  230,  230,  154,  140,
      230,  240,  240,  239,  230,  234,  234,  234,  234,  234,
      229,  239,  236,  236,  236,  236,  236,  240,  234,  139,
      234,  138,  137,  135,  134,  240,  133,  132,  131,  234,

      229,  130,  129,  234,  230,  234,  236,  238,  238,  238,
      238,  238,  243,  243,  243,  243,  243,  128,  127,  310,
      238,  126,  238,  125,  230,  243,  310,  243,  124,  123,
      248,  238,  122,  248,  121,  238,  243,  238,  119,  118,
      243,  310,  243,  245,  245,  245,  245,  245,  248,  248,
      117,  116,  251,  115,  251,  114,  248,  251,  251,  251,
      251,  251,  252,  252,  252,  252,  252,  245,  256,  256,
      113,  248,  112,  252,  252,  252,  252,  252,  255,  255,
      255,  255,  255,  111,  256,  110,  252,  257,  257,  109,
      261,  108,  256,  261,  265,  265,  265,  265,  265,  107,

      106,  105,  255,  257,  103,   98,   79,   71,  261,  261,
       70,  257,   69,   63,   58,   57,  261,   51,  265,   50,
       46,  263,  263,  263,  263,  263,  302,  302,  302,  302,
      302,  261,  263,  263,  263,  263,  263,   43,   39,  302,
       36,  302,   35,   32,   29,  263,   26,   18,   13,   10,
      302,    9,    5,    0,  302,    0,  302,  303,  303,  303,
      303,  303,  304,  304,  304,  304,  304,  305,  305,  305,
      305,  305,    0,    0,    0,  304,    0,  304,    0,    0,
        0,  303,    0,    0,    0,    0,  304,    0,    0,    0,
      304,  305,  304,  307,  307,  307,  307,  307,  308,  308,

      308,  308,  308,    0,  307,  307,  307,  307,  307,  309,
      309,  309,  309,  309,    0,    0,    0,  307,    0,    0,
        0,    0,  309,    0,  309,    0,  340,  340,  340,  340,
      340,    0,    0,  309,    0,    0,    0,  309,    0,  309,
      311,  311,  311,  311,  311,  338,  338,  338,  338,  338,
      340,  311,  311,  311,  311,  311,    0,    0,  338,    0,
      338,    0,    0,    0,  311,    0,    0,    0,    0,  338,
        0,    0,    0,  338,    0,  338,  381,  381,  381,  381,
      381,  381,  381,  381,  382,  382,  382,  382,  382,  382,
      382,  382,  383,    0,  383,  383,    0,  383,  384,  384,

      384,  384,  384,  384,  384,  384,  385,    0,  385,  385,
      385,  385,  385,  385,  386,  386,  386,    0,  386,  387,
      387,  387,    0,  387,  388,  388,  388,  388,  388,  388,
        0,  388,  389,    0,    0,  389,  391,    0,    0,  391,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[99] =
    {   0,
0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include<bits/stdc++.h>
using namespace std;
#include "parser.tab.h"
#include "symbol_table.h"


#line 853 "lex.yy.c"

#line 855 "lex.yy.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 149 "lexer.l"


#line 1076 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 381 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1041 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 151 "lexer.l"
{BEGIN comment;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 152 "lexer.l"
{BEGIN 0;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 153 "lexer.l"
//
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 155 "lexer.l"
{}        
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 156 "lexer.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 157 "lexer.l"
{strcpy(yylval.item.label,yytext); return TRIPLE_DOT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 158 "lexer.l"
{strcpy(yylval.item.label,yytext); return AMPERSAND;} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 159 "lexer.l"
{strcpy(yylval.item.label,yytext); return AMPERSAND_AMPERSAND;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 160 "lexer.l"
{strcpy(yylval.item.label,yytext); return AMPERSAND_EQUALS;} 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 161 "lexer.l"
{strcpy(yylval.item.label,yytext); return ARROW_RIGHT;}  
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 162 "lexer.l"
{strcpy(yylval.item.label,yytext); return BAR;}  
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 163 "lexer.l"
{strcpy(yylval.item.label,yytext); return BAR_BAR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 164 "lexer.l"
{strcpy(yylval.item.label,yytext); return BAR_EQUALS;}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 165 "lexer.l"
{strcpy(yylval.item.label,yytext); return CHARACTER_LITERAL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 166 "lexer.l"
{strcpy(yylval.item.label,yytext); return COLON;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 167 "lexer.l"
{strcpy(yylval.item.label,yytext); return COMMA;}   
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 168 "lexer.l"
{strcpy(yylval.item.label,yytext); return DOT;}   
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 169 "lexer.l"
{strcpy(yylval.item.label,yytext); return DOUBLE_COLON;} 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 170 "lexer.l"
{strcpy(yylval.item.label,yytext); return EQUALS;} 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 171 "lexer.l"
{strcpy(yylval.item.label,yytext); return EQUALS_EQUALS;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 172 "lexer.l"
{strcpy(yylval.item.label,yytext); return EXCLAIM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 173 "lexer.l"
{strcpy(yylval.item.label,yytext); return EXCLAIM_EQUALS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 174 "lexer.l"
{strcpy(yylval.item.label,yytext); return FLOATINGPOINT_LITERAL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 175 "lexer.l"
{strcpy(yylval.item.label,yytext); return GREATER_THAN;} 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 176 "lexer.l"
{strcpy(yylval.item.label,yytext); return GREATER_THAN_EQUALS;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 177 "lexer.l"
{strcpy(yylval.item.label,yytext); return GREATER_THAN_GREATER_THAN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 178 "lexer.l"
{strcpy(yylval.item.label,yytext); return GREATER_THAN_GREATER_THAN_EQUALS;} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 179 "lexer.l"
{strcpy(yylval.item.label,yytext); return GREATER_THAN_GREATER_THAN_GREATER_THAN;} 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 180 "lexer.l"
{strcpy(yylval.item.label,yytext); return GREATER_THAN_GREATER_THAN_GREATER_THAN_EQUALS;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 181 "lexer.l"
{strcpy(yylval.item.label,yytext); return LEFT_CURLY_BRACE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 182 "lexer.l"
{strcpy(yylval.item.label,yytext); return LEFT_PARANTHESIS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 183 "lexer.l"
{strcpy(yylval.item.label,yytext); return LEFT_SQUARE_BRACE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 184 "lexer.l"
{strcpy(yylval.item.label,yytext); return LESS_THAN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 185 "lexer.l"
{strcpy(yylval.item.label,yytext); return LESS_THAN_EQUALS;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 186 "lexer.l"
{strcpy(yylval.item.label,yytext); return LESS_THAN_LESS_THAN;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 187 "lexer.l"
{strcpy(yylval.item.label,yytext); return LESS_THAN_LESS_THAN_EQUALS;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 188 "lexer.l"
{strcpy(yylval.item.label,yytext); return MINUS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 189 "lexer.l"
{strcpy(yylval.item.label,yytext); return MINUS_EQUALS;}  
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 190 "lexer.l"
{strcpy(yylval.item.label,yytext); return MINUS_MINUS;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 191 "lexer.l"
{strcpy(yylval.item.label,yytext); return PACKAGE;}   
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 192 "lexer.l"
{strcpy(yylval.item.label,yytext); return PERCENT;} 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 193 "lexer.l"
{strcpy(yylval.item.label,yytext); return PERCENT_EQUALS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 194 "lexer.l"
{strcpy(yylval.item.label,yytext); return PLUS;}           
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 195 "lexer.l"
{strcpy(yylval.item.label,yytext); return PLUS_EQUALS;}  
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 196 "lexer.l"
{strcpy(yylval.item.label,yytext); return PLUS_PLUS;}   
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 197 "lexer.l"
{strcpy(yylval.item.label,yytext); return POWER;}   
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 198 "lexer.l"
{strcpy(yylval.item.label,yytext); return POWER_EQUALS;}   
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 199 "lexer.l"
{strcpy(yylval.item.label,yytext); return QUESTION;}   
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 200 "lexer.l"
{strcpy(yylval.item.label,yytext); return RIGHT_CURLY_BRACE;}   
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 201 "lexer.l"
{strcpy(yylval.item.label,yytext); return RIGHT_PARANTHESIS;}   
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 202 "lexer.l"
{strcpy(yylval.item.label,yytext); return RIGHT_SQUARE_BRACE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 203 "lexer.l"
{strcpy(yylval.item.label,yytext); return SEMI_COLON;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 204 "lexer.l"
{strcpy(yylval.item.label,yytext); return SLASH;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 205 "lexer.l"
{strcpy(yylval.item.label,yytext); return SLASH_EQUALS;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 206 "lexer.l"
{strcpy(yylval.item.label,yytext); return STAR;}    
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 207 "lexer.l"
{strcpy(yylval.item.label,yytext); return STAR_EQUALS;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 208 "lexer.l"
{strcpy(yylval.item.label,yytext); return YIELD;}    
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 209 "lexer.l"
{strcpy(yylval.item.label,yytext); return WHILE;}    
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 210 "lexer.l"
{strcpy(yylval.item.label,yytext); return VOID;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 211 "lexer.l"
{strcpy(yylval.item.label,yytext); return VAR;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 212 "lexer.l"
{strcpy(yylval.item.label,yytext); return TRY;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 213 "lexer.l"
{strcpy(yylval.item.label,yytext); return TILDA;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 214 "lexer.l"
{strcpy(yylval.item.label,yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 215 "lexer.l"
{strcpy(yylval.item.label,yytext); return TEXTBLOCK;}    
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 216 "lexer.l"
{strcpy(yylval.item.label,yytext); return THROWS;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 217 "lexer.l"
{strcpy(yylval.item.label,yytext); return THROW;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 218 "lexer.l"
{strcpy(yylval.item.label,yytext); return SYNCHRONIZED;}    
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 219 "lexer.l"
{strcpy(yylval.item.label,yytext); return SUPER;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 220 "lexer.l"
{strcpy(yylval.item.label,yytext); return STATIC;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 221 "lexer.l"
{strcpy(yylval.item.label,yytext); return RETURN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 222 "lexer.l"
{strcpy(yylval.item.label,yytext); return PUBLIC;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 223 "lexer.l"
{strcpy(yylval.item.label,yytext); return PRIVATE;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 224 "lexer.l"
{strcpy(yylval.item.label,yytext); return PERMITS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 225 "lexer.l"
{strcpy(yylval.item.label,yytext); return NULL_LITERAL;}    
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 226 "lexer.l"
{strcpy(yylval.item.label,yytext); return NEW;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 227 "lexer.l"
{strcpy(yylval.item.label,yytext); return INTERFACE;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 228 "lexer.l"
{strcpy(yylval.item.label,yytext); return INTEGRAL_TYPE;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 229 "lexer.l"
{strcpy(yylval.item.label,yytext); return IMPORT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 230 "lexer.l"
{strcpy(yylval.item.label,yytext); return IMPLEMENTS;}    
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 231 "lexer.l"
{strcpy(yylval.item.label,yytext); return IF;}    
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 232 "lexer.l"
{strcpy(yylval.item.label,yytext); return FOR;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 233 "lexer.l"
{strcpy(yylval.item.label,yytext); return FLOAT_POINT_TYPE;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 234 "lexer.l"
{strcpy(yylval.item.label,yytext); return FINALLY;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 235 "lexer.l"
{strcpy(yylval.item.label,yytext); return FINAL;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 236 "lexer.l"
{strcpy(yylval.item.label,yytext); return EXTENDS;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 237 "lexer.l"
{strcpy(yylval.item.label,yytext); return ELSE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 238 "lexer.l"
{strcpy(yylval.item.label,yytext); return CONTINUE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 239 "lexer.l"
{strcpy(yylval.item.label,yytext); return CLASS;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 240 "lexer.l"
{strcpy(yylval.item.label,yytext); return CATCH;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 241 "lexer.l"
{strcpy(yylval.item.label,yytext); return BREAK;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 242 "lexer.l"
{strcpy(yylval.item.label,yytext); return BOOLEAN_TYPE;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 243 "lexer.l"
{strcpy(yylval.item.label,yytext); return BOOLEAN_LITERAL;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 244 "lexer.l"
{strcpy(yylval.item.label,yytext); return ASSERT;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 245 "lexer.l"
{strcpy(yylval.item.label,yytext); return STRING_TYPE;}
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 246 "lexer.l"
{strcpy(yylval.item.label,yytext); return STRING_LITERAL;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 247 "lexer.l"
{strcpy(yylval.item.label,yytext); return IDENTIFIER;}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 248 "lexer.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
#line 249 "lexer.l"
{yyterminate();}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 253 "lexer.l"
ECHO;
	YY_BREAK
#line 1644 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 381 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 381 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 380);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 253 "lexer.l"


int yywrap() {
    return 1;
}
